version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    build: ./db
    environment:
      - POSTGRES_USER=dcpayrolladmin
      - POSTGRES_PASSWORD=maxmax
      - POSTGRES_DB=dcpayrolldb
    ports:
      - "5432:5432"