version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    build: ./db
    environment:
      - POSTGRES_USER=dpadmin
      - POSTGRES_PASSWORD=dppassword
      - POSTGRES_DB=dpdb
    ports:
      - "5432:5432"